name: Qodana for Pull Request
on:
 pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
      - 'Hi3Helper.Core/Lang/**.json'
      - 'Docs/**'
      - '**/packages.lock.json'