name: Publish Stable & Preview builds to WinGet
on:
  release:
    types: [released]
jobs:
  determine_channel:
    runs-on: ubuntu-latest
    outputs:
      channel: ${{ steps.check.outputs.channel }}
      version: ${{ steps.check.outputs.version }}
    steps:
      - name: Check Release Name and Extract Version
        id: check
        run: |
          RELEASE_NAME="${{ github.event.release.name }}"
          # Find X.Y.Z version, then check for "Preview" after it for regex
          if [[ "$RELEASE_NAME" =~ (\d+\.\d+\.\d+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            echo "Error: Could not find X.Y.Z version in release name."
            exit 1
          fi

          if [[ "$RELEASE_NAME" == *"Preview"* ]]; then
            CHANNEL="Preview"
          else
            CHANNEL="Stable"
          fi

          echo "Detected Channel: $CHANNEL"
          echo "Detected Version: $VERSION"
          echo "channel=$CHANNEL" >> $GITHUB_OUTPUT
          echo "version=$VERSION" >> $GITHUB_OUTPUT
  
  publish_stable:
    needs: determine_channel
    if: needs.determine_channel.outputs.channel == 'Stable'
    runs-on: windows-latest
    steps:
      - name: Publish CollapseLauncher.Collapse (Stable) to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: CollapseLauncher.Collapse # <--- Corrected Stable ID
          version: ${{ needs.determine_channel.outputs.version }}
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
          
  publish_preview:
    needs: determine_channel
    if: needs.determine_channel.outputs.channel == 'Preview'
    runs-on: windows-latest
    steps:
      - name: Publish CollapseLauncher.Collapse.Preview to WinGet
        uses: vedantmgoyal9/winget-releaser@main
        with:
          identifier: CollapseLauncher.Collapse.Preview
          version: ${{ needs.determine_channel.outputs.version }}
          installers-regex: '\.exe$'
          token: ${{ secrets.WINGET_TOKEN }}
